// Generated by CoffeeScript 1.3.3

/*
Basic web server in Node.js + Express
*/


(function() {
  var app, fs, port, server, _ref;

  app = require("express")();

  fs = require("fs");

  server = require("http").createServer(app);

  port = (_ref = process.env.PORT) != null ? _ref : 5000;

  server.listen(port);

  app.get(/(.*)/, function(request, response) {
    var filePath;
    filePath = request.params[0];
    if (filePath === "/") {
      filePath = "index.html";
    }
    if (filePath.substr(0, 1) !== "/") {
      filePath = "/" + filePath;
    }
    filePath = __dirname + filePath;
    if (fs.existsSync(filePath)) {
      return response.sendfile(filePath);
    }
  });

  app.post("/verify/:email", function(request, response) {
    if (typeof console !== "undefined" && console !== null) {
      console.log("Request: " + request.params.email);
    }
    return response.send({
      result: "OK"
    });
  });

}).call(this);
