// Generated by CoffeeScript 1.3.3

/*
Basic web server in Node.js + Express
*/


(function() {
  var app, fs, nodemailer, port, server, smtpTransport, verificationMessage, _ref;

  app = require("express")();

  fs = require("fs");

  server = require("http").createServer(app);

  nodemailer = require("nodemailer");

  port = (_ref = process.env.PORT) != null ? _ref : 5000;

  server.listen(port);

  app.get(/(.*)/, function(request, response) {
    var filePath;
    filePath = request.params[0];
    if (filePath === "/") {
      filePath = "index.html";
    }
    if (filePath.substr(0, 1) !== "/") {
      filePath = "/" + filePath;
    }
    filePath = "" + __dirname + "/client" + filePath;
    if (typeof console !== "undefined" && console !== null) {
      console.log("get: " + filePath);
    }
    if (fs.existsSync(filePath)) {
      return response.sendfile(filePath);
    }
  });

  smtpTransport = nodemailer.createTransport("SMTP", {
    service: "Gmail",
    auth: {
      user: "copper.mailer@gmail.com",
      pass: "copper.mailer"
    }
  });

  verificationMessage = {
    from: "Copper <copper.mailer@gmail.com>",
    subject: "Department of Unified Protection email verification required",
    text: "Hello world!",
    html: "Hello <i>world</i>!"
  };

  app.post("/verify/:email", function(request, response) {
    var _this = this;
    if (typeof console !== "undefined" && console !== null) {
      console.log("Sending verification message to " + request.params.email);
    }
    verificationMessage.to = request.params.email;
    return smtpTransport.sendMail(verificationMessage, function(error, result) {
      var confirmation;
      confirmation = {};
      if (error) {
        confirmation.sent = false;
        confirmation.error = error;
      } else {
        confirmation.sent = true;
      }
      return response.send(confirmation);
    });
  });

}).call(this);
