// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.FacebookPage = (function(_super) {

    __extends(FacebookPage, _super);

    function FacebookPage() {
      return FacebookPage.__super__.constructor.apply(this, arguments);
    }

    FacebookPage.prototype.inherited = [
      {
        html: "div",
        ref: "globalContainer",
        content: [
          {
            html: "div",
            ref: "contentArea",
            content: [
              {
                html: "div",
                ref: "FacebookPage_content"
              }
            ]
          }
        ]
      }
    ];

    FacebookPage.prototype.content = Control.chain("$FacebookPage_content", "content");

    return FacebookPage;

  })(Page);

  window.ProfilePage = (function(_super) {

    __extends(ProfilePage, _super);

    function ProfilePage() {
      return ProfilePage.__super__.constructor.apply(this, arguments);
    }

    ProfilePage.prototype.inherited = {
      content: "Ann Wiliams"
    };

    return ProfilePage;

  })(FacebookPage);

}).call(this);
